apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: analytics-service
  name: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: analytics-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: analytics-service
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/
            - name: MYSQL_DB
              value: data_collection
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: user
            - name: PORT
              value: "5003"
          image: costhm/analytics-service:latest
          name: analytics-service
          ports:
            - containerPort: 5003
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always
