apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: data_collection
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: user
            - name: JWT_SECRET_KEY
              value: supersecretkey
            - name: ENTER_DATA
              value: enter-data
          image: rylanraj/auth_service:latest
          name: auth-service
          ports:
            - containerPort: 5001
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      restartPolicy: Always
