apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: enter-data
  name: enter-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: enter-data
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: enter-data
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: data_collection
            - name: DB_PASSWORD
              value: password
            - name: DB_USER
              value: user
            - name: PORT
              value: "5002"
          image: costhm/enter-data:latest
          name: enter-data
          ports:
            - containerPort: 5002
              protocol: TCP
      restartPolicy: Always
